version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: pyspark
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: abatilo/actions-poetry
